package com.entity;
// Generated 2017-6-4 10:51:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "shtp")
public class Category implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String descb;
	private Set<Goods> goods = new HashSet<Goods>(0);

	public Category() {
	}

	public Category(String name, String descb, Set<Goods> goods) {
		this.name = name;
		this.descb = descb;
		this.goods = goods;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descb")
	public String getDescb() {
		return this.descb;
	}

	public void setDescb(String descb) {
		this.descb = descb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Goods> getGoodses() {
		return this.goods;
	}

	public void setGoodses(Set<Goods> goods) {
		this.goods = goods;
	}

}
