package com.entity;
// Generated 2017-6-4 11:10:03 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.struts2.json.annotations.JSON;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "shtp")
public class Comment implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Goods goods;
	private Member member;
	private Date commentTime;
	private String commentContent;
	

	public Comment() {
	}

	public Comment(Goods goods, Member member, Date commentTime, String commentContent) {
		this.goods = goods;
		this.member = member;
		this.commentTime = commentTime;
		this.commentContent = commentContent;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods", nullable = false)
	@JSON(serialize=false)
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "u_id", nullable = false)
	@JSON(serialize=false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_date", nullable = false, length = 19)
	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	@Column(name = "c_content", nullable = false, length = 65535)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	

}
