package com.entity;
// Generated 2017-6-4 10:51:05 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.struts2.json.annotations.JSON;

/**
 * Complain generated by hbm2java
 */
@Entity
@Table(name = "complain", catalog = "shtp")
public class Complain implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Member memberByBuyer;
	
	
	private Date complainTime;
	private String complainContent;
	

	public Complain() {
	}

	public Complain(Member memberByBuyer,  Date complainTime, String complainContent) {
		this.memberByBuyer = memberByBuyer;
		this.complainTime = complainTime;
		this.complainContent = complainContent;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "com_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "u_id")
	@JSON(serialize=false)
	public Member getMemberByBuyer() {
		return this.memberByBuyer;
	}

	public void setMemberByBuyer(Member memberByBuyer) {
		this.memberByBuyer = memberByBuyer;
	}

	


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "com_date", length = 19)
	public Date getComplainTime() {
		return this.complainTime;
	}

	public void setComplainTime(Date complainTime) {
		this.complainTime = complainTime;
	}

	@Column(name = "com_content", length = 65535)
	public String getComplainContent() {
		return this.complainContent;
	}

	public void setComplainContent(String complainContent) {
		this.complainContent = complainContent;
	}


}
