package com.entity;
// Generated 2017-6-4 10:51:05 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "shtp")
public class Member implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String username;
	private String password;
	private Integer permission;
	private String name;
	private String gender;
	private Date birthday;
	private String phone;
	private String address;
	private Date registerTime;
	private Date lastLoginTime;
	
	private Set<Orders> orders = new HashSet<Orders>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Complain> complainsForBuyer = new HashSet<Complain>(0);
	private Set<Goods> goods = new HashSet<Goods>(0);
	private Set<Return> returns = new HashSet<Return>(0);
	public Member() {
	}

	public Member(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Member(String username, String password, Integer permission, String name, String gender, Date birthday,
			String phone, String address, Date registerTime, Date lastLoginTime, Set<Orders> orders,
			Set<Comment> comments, Set<Complain> complainsForBuyer, Set<Goods> goods,Set<Return> returns) {
		this.username = username;
		this.password = password;
		this.permission = permission;
		this.name = name;
		this.gender = gender;
		this.birthday = birthday;
		this.phone = phone;
		this.address = address;
		this.registerTime = registerTime;
		this.lastLoginTime = lastLoginTime;
	
		this.orders = orders;
		this.comments = comments;
		this.complainsForBuyer = complainsForBuyer;
		this.goods = goods;
		this.returns = returns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "permission")
	public Integer getPermission() {
		return this.permission;
	}

	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gender", length = 2)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registerTime", length = 19)
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastLoginTIme", length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Comment> getComments() {
		return comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Orders> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Orders> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberByBuyer")
	public Set<Complain> getComplainsForBuyer() {
		return this.complainsForBuyer;
	}

	public void setComplainsForBuyer(Set<Complain> complainsForBuyer) {
		this.complainsForBuyer = complainsForBuyer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Goods> getGoods() {
		return this.goods;
	}

	public void setGoods(Set<Goods> goods) {
		this.goods = goods;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Return> getReturns() {
		return returns;
	}

	public void setReturns(Set<Return> returns) {
		this.returns = returns;
	}

	

}
