package com.entity;
// Generated 2017-6-4 10:51:05 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.struts2.json.annotations.JSON;

/**
 * Orders generated by hbm2java
 */
@Entity       //指定类是持久化类
@Table(name = "return", catalog = "shtp")    //��return�ı���
public class Return implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	
	private Goods goods;
	
	private Member member;
	private Date returnTime;
	//private String tradingSatuts;
	private String reason;

	public Return() {
	}

	public Return(Goods goods, Member member, Date returnTime,  String reason) {
		this.goods = goods;
		this.member = member;
		this.returnTime= returnTime;
		//this.tradingSatuts = tradingSatuts;
		this.reason = reason;
	}

	
	//@Id声明实体类的属�?       映射�?               数据库的主键�?
	//@GeneratedValue(strategy = IDENTITY)  标注逐渐的生成策�?  IDENTITY自增
	//@Column标识实体类中属�?        �?     数据库表字段       的对应关�?
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "r_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	//再使用@ManyToOne  @JoinColumn实现Orders到Goods的多对一关联    LAZY标识关联了在被访问时才加�?
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "g_id")       //外键
	//过滤不需要的变量               struts2返回Json类型的数据时 json会自动转换成json形式的变�?  如果哪个变量不需要时使用该注�?
	@JSON(serialize=false)
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}
	//再使用@ManyToOne  @JoinColumn实现Orders到Member的多对一关联    LAZY标识关联了在被访问时才加�?
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "u_id")      //外键
	//过滤不需要的变量               struts2返回Json类型的数据时 json会自动转换成json形式的变�?  如果哪个变量不需要时使用该注�?
	@JSON(serialize=false)          
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}
    
	/*@Column(name = "trading_satuts", length = 2)
	public String getTradingSatuts() {
		return this.tradingSatuts;
	}	
		public void setTradingSatuts(String tradingSatuts) {
		this.tradingSatuts = tradingSatuts;
	}
	*/
	
	 //格式化时间日期，页面直接得到格式化类型的�?
		@Temporal(TemporalType.TIMESTAMP)
		//@Column标识实体类中属�?与数据库表字段的对应关系
		@Column(name = "r_date", length = 19)
		
	public Date getReturnTime() {
		return returnTime;
	}

	public void setReturnTime(Date returnTime) {
		this.returnTime = returnTime;
	}
	
	@Column(name = "r_reason")
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	

	
	

}
